### ISSUE TITLE
Allow a consumer of the library to specify all fields of a `Note` directly

### ISSUE THREAD

**Issue by jules** [dusk-network/phoenix#10]
This functionality is needed in order to successfully decode a `Note` from a GRPC connection. Currently, the library only offers the option to supply some "pre-image" variables, which are then turned into the proper fields by using some function.

The stealth address is a good example of this: in `Note::deterministic`, you can only supply the public spend key and the random scalar that make up this stealth address - variables that you will not have if you are just decoding a Note from GRPC.

**Comment by julesdesmit** [comment]
Closing this issue, as another way was found to decode notes.
