### ISSUE TITLE
Avoid redefinition of types in different crates

### ISSUE THREAD

**Issue by ureeves** [dusk-network/phoenix#121]
#### Summary
We should try and avoid redefining types defined in other crates, or using "untyped" fields. Currently the `Transaction::proof` field is a `Vec<u8>`, when it really should be a `dusk_plonk::Proof`, and there is also a `ModuleId` type alias that really should be `piecrust_uplink::ModuleId`.

#### Possible solution design or implementation
One possible solution is to include the appropriate dependencies, even at the risk of increasing binary size for users of this crate.

#### Additional context

_Although this is clearly an improvement to the previous version where we don't add a type alias and only use `BlsScalars` as an ID, wouldn't it make sense to use the piecrust `ModuleId` here even though it would include an extra dependency? 
It doesn't feel 'right' to define the same thing in two different crates._

_Originally posted by @moCello in https://github.com/dusk-network/phoenix-core/pull/120#discussion_r1081274067_

**Comment by ureeves** [comment]
There's multiple instances of this in this crate already, introduced with the smart contract types. The `proof` field and `ModuleId` are examples.
My recommendation would be pulling in the appropriate dependencies.

**Comment by moCello** [comment]
closed as no longer relevant after the re-design in #171 and #175
