### ISSUE TITLE
`SecretKey` should be enough to verify note's ownership

### ISSUE THREAD

**Issue by ZER0** [dusk-network/phoenix#146]
#### Summary
We created the `ViewKey` as a way to delegate the ownership check, however we don't always do that: for example, in the current implementation of the wallet (CLI and web) we're verifying the note locally.
In order to do so, we need to create a `ViewKey` even if we have access to a `SecretKey`, that should be enough to verify the note's ownership.

#### Possible solution design or implementation
As the `ViewKey` has, the `SecretKey` should implement the `owns` method as well.

#### Additional context
The hope is to reduce not only the code involved, but at least a bit of the operations too.

**Comment by autholykos** [comment]
@xevisalle @ZER0 is this superseded by the light sync mechanism? Can I close this?

**Comment by xevisalle** [comment]
@autholykos it has nothing to do, this is about not requiring the view key to sync if we already have the secret key instantiated. The development is almost done here: https://github.com/dusk-network/phoenix/issues/200
