### ISSUE TITLE
Be more specific in our error definitions/usage

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/phoenix#40]
As it was referenced by @zer0 in #39 we might want to refactor the error usage in Phoenix & other libs of our stack in order to be more specific. 

See: 
It's okay because you've been consistent within the repos, but I think we start to have more clear errors for such scenarios: "InvalidXXXConversion" doesn't tell why. Here the error is that we don't have enough bytes into the buffer for actually even trying a conversion.

You can search for similar code in our repos, and get an inspiration for what I mean, we might want to refactor this also in the future.

_Originally posted by @ZER0 in https://github.com/dusk-network/phoenix-core/pull/39#discussion_r536059676_

**Comment by moCello** [comment]
Closing as no longer relevant
